### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DatDerpyDude81** [Quartinal/INSECURLY#2]
Hey there, is this deployable on github pages or will I need something that works with backend.

**Comment by Quartinal** [comment]
Hello, @DatDerpyDude81! This is all HTML, CSS, and JavaScript, which are frontend languages. You can fork it to deploy it to GitHub Pages, and if you do, feel free to open pull requests!

**Comment by DatDerpyDude81** [comment]
Alright, Thanks!
